version: '3'
   
services:
  db:
    container_name: db
    image: postgres:13.3
    volumes:
      - .:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    networks: 
      - django_db_net

  server:
    build: ./
    container_name: server
    command: python manage.py runserver localhost:8000
    ports:
      - "8000:8000"
    volumes:
      - server:/server
    depends_on:
      - db
    networks: 
      - django_db_net
    restart: on-failure
volumes:
  server:
networks:
  django_db_net:
