version: '2'
   
services:
  db:
    container_name: boards_db
    image: postgres:13.3
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    networks: 
      - django_db_net

  server:
    build: server/
    container_name: boards_server
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:${SERVER_PORT}"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./server/:/home/server
      - ../media_storage:/home/server/boards/media/
    env_file:
      - .env
    depends_on:
      - db
    networks: 
      - django_db_net
    restart: on-failure

  redis:
    container_name: boards_redis
    image: redis:6.2
    restart: always
  
volumes:
  db:
  media_storage:
  server:
networks:
  django_db_net:
