version: '3'
   
services:
  db:
    container_name: db
    image: postgres:13.3
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    networks: 
      - django_db_net

  server:
    build: .
    container_name: server
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/server
    depends_on:
      - db
    networks: 
      - django_db_net
    restart: on-failure
volumes:
  db:
networks:
  django_db_net:
