# Generated by Django 3.2.4 on 2021-07-12 11:59
from django.db import migrations
from accounts.models import GroupCreation



class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(GroupCreation.create),
    ]
