# Generated by Django 3.2.4 on 2021-07-12 11:59
from django.db import migrations
from accounts.choices import GroupChoices


def create_groups(apps, schema_editor):
    # Create users groups on migrate this migrations 
    Group = apps.get_model('auth', 'Group')
    Group.objects.bulk_create([Group(name=group_name) for group_name in GroupChoices.values]) # create all groups from GROUP_NAMES


def delete_groups(apps, schema_editor):
    # delete all groups on revert this migrations
    Group = apps.get_model('auth', 'Group')
    Group.objects.all().delete()



class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups, delete_groups),
    ]
