# Generated by Django 3.2.4 on 2021-07-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_creating_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Not selected'), (2, 'man'), (3, 'woman')], default=1),
        ),
    ]
