# Generated by Django 3.2.4 on 2021-07-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_creating_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('u', 'unknown'), ('m', 'man'), ('w', 'woman')], default='u', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/%H:%M:%S'),
        ),
    ]
