# Generated by Django 3.2.4 on 2021-07-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Not Selected'), (1, 'Man'), (2, 'Woman')], default=0),
        ),
    ]
