# Generated by Django 3.2.4 on 2021-07-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_board_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
