# Generated by Django 3.2.4 on 2021-06-14 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicmodel',
            old_name='user',
            new_name='owner',
        ),
    ]
